### PR TITLE
Platzi challenge - NewRelic

### PR DESCRIPTION
**Pull request by ApeWithGlasses**
# Platzi Challenge PR

## Description

- UI Redesign: Updated the user interface with new styles, colors, and fonts for a more modern and engaging user experience.
- Payment Method Update: Removed American Express as a payment option.
- Checkout Enhancement: Implemented an interactive card display during the checkout process to improve usability and clarity.
- Branding Refresh: Introduced a new logo generated using AI technology to modernize the brand identity.
- Performance Monitoring: Integrated New Relic monitoring tools to track application performance, identify potential issues, and optimize user experience.
- Featured Restaurant Addition: Added "La Tertulia," a renowned Colombian restaurant, to the platform's offerings.

<hr>

I put all my effort in this challenge, improving most of the styles, it was really fun and very enriching, I learned many new and interesting things, one of the parts that I found a little complicated was the newrelic part, there are several aspects such as versioning that generated some problems but I could solve them, thank you!

ps: I couldn't finish some things with newrelic because my platzi license from my institute expired but I learned a lot.

### CODE REVIEW

**Comment by ritarenee15** [comment]
Hey there! 😄 

Thank you for completing the challenge! 🎉 We've began judging the submissions, and it looks like we're unable to view your submission due to an error in your application when we attempt to run it.

We want to make sure we view your submission so it's considered for the challenge! If you need some help, feel free to reach out to Platzi support or [New Relic Student Support](https://forum.newrelic.com/s/hubtopic/Topic__c/Default?c__categories=%5B%7B%22icon%22%3A%22standard%3Adefault%22%2C%22id%22%3A%22a6cPh000000kD0fIAE%22%2C%22sObjectType%22%3A%22Category__c%22%2C%22title%22%3A%22Student%20Technical%20Support%22%2C%22titleFormatted%22%3A%22Student%20Technical%20Support%22%7D%5D). Please have the application updated by Wednesday, July 24th 12pm EST, as we will conclude the judging process at that time.

Thanks!
Rita

**Comment by ritarenee15** [comment]
Hi there, you can ignore the previous message. We were able to figure it out!

Thank you again for participating! We'll be announcing the winners next week!

Rita

**Comment by ApeWithGlasses** [comment]
Hi there! Let me know if anything goes wrong hehe, thank you for considering me!

**Comment by morganersery1** [comment]
Hello and thanks so much for your submission. We had several strong submissions for the challenge, but unfortunately, you were not one of our selected winners, but we appreciate your participation. There will be more chances to participate in the future for swag including opportunities coming up during our Back to School campaign. Sign up for the student newsletter, if you haven't already, for news of upcoming events and contests.

**Pull request closed without merging**
